# GOAL: call the workflows to deploy the project with CICD

name: CICD

on:
  push:

jobs:
  code-lint-frontend-Backend-Postgress_DB:
    uses: ./.github/workflows/code_lint_build_F_B_DB.yml

  BUild-an-image-of-docker-and-push-image-to-dockerhub:
    needs: code-lint-frontend-Backend-Postgress_DB
    secrets: inherit
    uses: ./.github/workflows/frontend_backend_docker_builld_and_push.yml

  Deploy:

    needs: [code-lint-frontend-Backend-Postgress_DB , BUild-an-image-of-docker-and-push-image-to-dockerhub ]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml

    
    

  