# Goal: build the docker image and push it to docker hub 

name: Build and push 

on: 
  push:

jobs:
  build-and-push-image-to-dockerhub:

    runs-on: ubuntu-latest

    steps:
      
      - name: code setup
        uses: actions/checkout@v7

      - name: docker setup
        uses: docker/setup-docker-action@v5  

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v4

       # Build and push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard_frontend:latest

      # Build and push backend
      - name: Build and push backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard_backend:latest 

